### ISSUE TITLE
Help needed: On-demand builder support

### ISSUE THREAD

**Issue by MarcelloTheArcane** [MarcelloTheArcane/netlify-plugin-csp-generator#17]
Netlify have announced on-demand builders: https://www.netlify.com/blog/2021/04/14/faster-builds-for-large-sites-on-netlify-with-on-demand-builders-now-in-early-access/

> With On-demand Builders you can split your site’s assets into two groups:
> - Critical content, that is automatically compiled and deployed as part of your traditional Netlify build process.
> - Deferred content, built using an on-demand builder when a site visitor requests it for the first time. This content is then cached at the edge, so it’s available to load more quickly for subsequent visitors.

Which sounds very cool, except it means that not all the paths will have CSP headers generated for them.

I'm not sure the best way around it, other than saying at the moment that this feature is incompatible with this plugin.

**Comment by jackdbd** [comment]
As they say [in the Netlify support forum](https://answers.netlify.com/t/faster-builds-for-large-sites-with-on-demand-builders/35933): 
> On-demand Builders are serverless functions used to generate web content on-demand that is automatically cached on Netlify’s Edge CDN. 

I might be mistaken, but I guess you can still add HTTP headers to the generated content. Otherwise this would be an issue not just for this plugin, but for all other Netlify plugins that hooks to the `onPostBuild` event...

Another thing that maybe you can use is a [Edge handler](https://docs.netlify.com/configure-builds/file-based-configuration/#edge-handlers). I'm just guessing, I've never used them, but triggering a function when the Netlify CDN is hit seems exactly what you need.

PS: nice plugin, I implemented a similar solution to scrape the `<style>` content of the generated HTML pages using [Himalaya](https://github.com/andrejewski/himalaya) instead of jsdom, but this plugin is much more feature-complete of what I've done.

**Comment by MarcelloTheArcane** [comment]
Hello @jackdbd!  Nice of you to drop by 😁

That's a good shout, I've replied to that forum post to ask about how `onPostBuild` hooks will work with it.  My concern is they could be very long-running, which would make the first on-demand load pretty slow.  But I'll see what they say.

I haven't heard of their edge triggers before, so that's really helpful and I'll have a look into that.

Thanks!  Himalaya looks great, I've definitely wanted an HTML-to-JSON parser before 😄

**Comment by jackdbd** [comment]
If you are interested, here is the code that extracts the content of all `<style>` tags in the `<head>`
https://github.com/jackdbd/personal-website/blob/e6b381a3dc73b4c310bf942f6b1e6902a07c027f/scripts/style-tags-contents.js

**Comment by MarcelloTheArcane** [comment]
[Sounds like it's not going to be possible](https://answers.netlify.com/t/faster-builds-for-large-sites-with-on-demand-builders/35933), so I'm closing this issue.

If there's any update from Netlify about this, I'll have another look - but it might even deserve it's own repository.
