### ISSUE TITLE
Feature request: Apply 404 page header to wildcard path

### ISSUE THREAD

**Issue by ccsaposs** [MarcelloTheArcane/netlify-plugin-csp-generator#4]
I have a 404 page located at `/404.html`.

Would it be possible to apply the CSP header for the 404 page to all paths?

Here's my `_headers` file before the plugin runs:
```
/*
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY

```
Here's my `_headers` file after the plugin runs:
```
/*
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
dist/404.html
  Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self'; manifest-src 'self'; script-src 'sha256-9iRTeQPDoAPORwIuPHfDUMUAr0uyvMTtzR85/74dCko=' 'self'; style-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none';
/
  Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self'; manifest-src 'self'; script-src 'sha256-JScAO1Thw3d59soeFvNNKhkXtu2ERtCvHSQ5YpgnWVo=' 'self'; style-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none';
/about/
  Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self'; manifest-src 'self'; script-src 'sha256-3bAlL4NiNZv/xLYFLu20C66ph3CMtp2shj8pblOFnrw=' 'self'; style-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none';
```
`dist/404.html` is an invalid path (since `dist` is the folder that Netlify deploys from [there is no `dist` folder on the website]).

Here's what I would like my `_headers` file to look like:
```
/*
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  Referrer-Policy: no-referrer
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self'; manifest-src 'self'; script-src 'sha256-9iRTeQPDoAPORwIuPHfDUMUAr0uyvMTtzR85/74dCko=' 'self'; style-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none';
/
  Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self'; manifest-src 'self'; script-src 'sha256-JScAO1Thw3d59soeFvNNKhkXtu2ERtCvHSQ5YpgnWVo=' 'self'; style-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none';
/about/
  Content-Security-Policy: default-src 'none'; font-src 'self'; img-src 'self'; manifest-src 'self'; script-src 'sha256-3bAlL4NiNZv/xLYFLu20C66ph3CMtp2shj8pblOFnrw=' 'self'; style-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none';
```

Is this possible?  Thank you for your time.

**Comment by MarcelloTheArcane** [comment]
What's your `buildDir` in your `[plugins.inputs]`? That should take away the `dist`.  

You can blacklist paths (the 404 page) with `exclude` in the `[plugins.inputs]`.  I don't use wildcard routes because the generated hashes are generally different.  You can put a wildcard CSP header in your `_headers` file if you like (I'm not sure what happens about precedence), but I'd recommend generating CSP headers for each path.

Have I understood correctly?

**Comment by ccsaposs** [comment]
`buildDir` is set to `dist`--should I change that?

The reason I'm trying to add a wildcard 404 is since any route that doesn't match to a specific route will return my 404 page, and I want to be able to allow the 404 script and style (while enforcing a CSP).

For `_headers`, it seems like the later header takes precedence.

**Comment by MarcelloTheArcane** [comment]
Is there any chance you could share your repository with me, so I can have a look?

**Comment by ccsaposs** [comment]
Here's the current branch I'm working on: https://github.com/ccsaposs/vom-website/tree/nuxt.  It's a bit messy, please let me know if you have any questions.

`_headers` are in `static/`

**Comment by MarcelloTheArcane** [comment]
@ccsaposs thanks, that's helped.  I've found out what the issue is - it's this line:

https://github.com/MarcelloTheArcane/netlify-plugin-csp-generator/blob/4fc53afb6695a3b2de7d42e70757ac5a3c56e84c/index.js#L77

I replace all file paths ending in `index.html` because the netlify `_headers` doesn't work with it added.  However, some routes generated by nuxt use numeric errors, like `404.html`, `500.html` etc.

This is a problem, because if I remove the numeric part, all these error pages *and* the root `/` page will match.

I'll need to add them all to the `/*` route in `_headers` as you suggested, which I'll have a look at tomorrow. (Note to self - I'll need to make sure *all* the script hashes are there)

Thanks for raising this, I'll try to fix as soon as possible.

**Comment by ccsaposs** [comment]
Thank you so much for your help!

**Comment by MarcelloTheArcane** [comment]
@ccsaposs I've merged that pull request, which closed this issue.  I've updated to version 1.2.0 on NPM.

If you're still seeing the same problem, please reopen this issue - hopefully it is fixed.

**Comment by ccsaposs** [comment]
It's working!  Thank you so much for your help, we really appreciate it!
